basic_usage.md

Update documentation to reflect change in flag.

-n flag has changed to nightly

---

SUMMARY.md
acceleration.md

Easy walk through to help users get CPU virtualization hardware support working.

Add Linux & macOS CPU virt support docs.

---

acceleration.md

Grammar fix and update to match https://github.com/nanovms/ops/commit/4a9e3557c46b406fb3a0867eac3fceee9f837bcc.

Key change and grammar fix.

---

SUMMARY.md
configuration.md
google_cloud.md

Add instructions about
1. CloudConfig - Cloud provider config
2. Create an image in Google Cloud Platform
3. Create an instance from an existing image

Issue #40: Add info about Google Cloud Integration

---

basic_usage.md

Signed-off-by: Craig S. Cottingham <craig@cottingham.net>

Issue #71: ops list -> ops pkg list

---

aws.md
openstack.md

1. Added examples for providing custom ports on AWS.
2. Added examples in openstack for providing volume size and flavor.
@eyberg please let me know if you need any changes or if you want to add more information.

Updated documentation as per recent changes.

---

configuration.md

add runconfig and cloudconfig documentation

---

SUMMARY.md
virtual_box.md

add virtual box initial documentation

---

SUMMARY.md
terraform.md

add terraform notes

---

firecracker.md

cf. https://github.com/nanovms/ops/pull/595
```
» find /root/.ops/ | grep .img
/root/.ops/0.1.34/kernel.img
/root/.ops/0.1.34/boot.img
/root/.ops/images/03-http-hello-world.img
/root/.ops/nightly/kernel.img
/root/.ops/nightly/boot.img
```

firecracker: rename stage3.img to kernel.img

---

instances.md

I had to look up the command in the source code for "ops instance", so figured I'd update the docs.

Instance documentation page

---

digital_ocean.md
vultr.md

Reflects https://github.com/nanovms/ops/pull/1185

DO/Vultr: differentiate token env variable name

---

images.md

adding image mirroring command

---

klibs.md

https://github.com/nanovms/ops/pull/1349

Klibs: NTP: update syntax for configuration options

---

klibs.md

Closes https://github.com/nanovms/ops-documentation/issues/340

klibs(cloud_init): add 'overwrite' flag usage, expand caveats

---

configuration.md
google_cloud.md

Closes https://github.com/nanovms/ops-documentation/issues/354
```json
{
"RunConfig": {
"CanIPForward": true
}
}
```

configuration: add RunConfig.CanIPForward (gcp)

---

klibs.md

resolves https://github.com/nanovms/ops-documentation/issues/358

klibs(cloud_init): add 'auth' config

---

configuration.md

https://github.com/nanovms/nanos/pull/1819

adding in docs for ipv4_wait

---

configuration.md

resolves https://github.com/nanovms/ops-documentation/issues/372

configuration: add CloudConfig.DedicatedHostId (aws)

---

source-installation.md

resolves https://github.com/nanovms/ops-documentation/issues/373
resolves https://github.com/nanovms/ops-documentation/issues/374

source-installation: add build tags and protobuf information

---

packages.md

resolve https://github.com/nanovms/ops-documentation/issues/362

packages: ops pkg from-run

---

klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/365 , unless specific vault example required

klibs: cloud_init.download_env added

---

klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/368

klibs: add Firewall

---

configuration.md

resolve https://github.com/nanovms/ops-documentation/issues/379

configuration: add ManifestPassthrough.program_overwrite

---

configuration.md

resolve https://github.com/nanovms/ops-documentation/issues/330

configuration: add ManifestPassthrough.trace

---

configuration.md

This is a PR to make the linter happy and to add the `consoles` config options in the MainfestPassthrough section

make the linting happy and add consoles config information

---

configuration.md
klibs.md

https://github.com/nanovms/ops/pull/1464

mv klibs config to top-level config

---

azure.md
configuration.md

resolve https://github.com/nanovms/ops-documentation/issues/390

azure: add ip forwarding

---

klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/367
maybe https://github.com/nanovms/ops-documentation/issues/369

klibs: add Sandbox - pledge, unveil

---

klibs.md

maybe https://github.com/nanovms/ops-documentation/issues/326

klib(ntp): expand minimum samples details

---

klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/401

klibs: clarify klibs folder location

---

cloud_hypervisor.md

resolve https://github.com/nanovms/ops-documentation/issues/387

cloud-hypervisor: initial notes

---

aws.md
klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/353
resolve https://github.com/nanovms/ops-documentation/issues/308
resolve https://github.com/nanovms/ops-documentation/issues/276 + https://docs.ops.city/ops/configuration#instanceprofile

klibs(cloudwatch): ManifestPassthrough.cloudwatch.(logging,mem_metrics_interval)

---

klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/343

klibs(radar): usage docs

---

configuration.md
klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/280

env(IMAGE_NAME): usage docs

---

configuration.md
volumes.md

resolve https://github.com/nanovms/ops-documentation/issues/364

config: Mounts using VirtFS VirtIO 9p

---

configuration.md

resolve https://github.com/nanovms/ops-documentation/issues/416

configuration: add RunConfig.AtExit

---

aws.md

https://github.com/nanovms/ops/pull/1507

skip verify docs

---

configuration.md

configuration: add exec_wait_for_ip6_secs, update exec_wait_for_ip4_secs

---

klibs.md

https://github.com/nanovms/nanos/pull/1947

klibs(gcp): disk metrics added

---

configuration.md

resolve https://github.com/nanovms/ops-documentation/issues/436

configuration: extended tags config

---

configuration.md

resolve https://github.com/nanovms/ops-documentation/issues/445

configuration: manifestpassthrough.reboot_on_exit - revised

---

images.md

resolve https://github.com/nanovms/ops-documentation/issues/449

images: ops image env - added

---

klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/447

klibs(ntp): PTP hardware clock - added

---

volumes.md

resolve https://github.com/nanovms/ops-documentation/issues/448
resolve https://github.com/nanovms/ops-documentation/issues/453

volumes: ops volume tree/ls/cp - added

---

volumes.md

volumes: ops volume info - added

---

configuration.md

Updated docs based on this: https://github.com/nanovms/ops/pull/1582

Clarified usage of VPC field in config for DO

---

examples.md

resolve https://github.com/nanovms/ops-documentation/issues/474

examples: add links to github.com/nanovms/ops-examples

---

klibs.md

resolve https://github.com/nanovms/ops-documentation/issues/476

klibs: add Azure

---

configuration.md

 configuration: manifestpassthrough.transparent_hugepage - disable THP

---

debugging.md

In addition, edit the instructions for debugging the user program, to reflect the fact that Ops now has integrated debug support and therefore editing the Ops source and starting Qemu manually are no longer needed.
Closes #500.

debugging.md: add instructions for debugging the Nanos kernel
